name: datetime_picker_formfield
description: A TextFormField that emits DateTimes and helps show Material, Cupertino, and other style picker dialogs.
version: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.4"

environment:
  sdk: '>=2.17.0 <3.0.0'
